"""Persona narrative library for Andy Bot email generation."""

from __future__ import annotations

PERSONAS = (
    "Discovery",
    "Translational / Clinical Development",
    "Biomarkers / Bioanalysis",
    "Clinical Pharmacology",
    "Medical Affairs",
    "Safety / Quality",
    "Oncology",
)

NARRATIVE_LIBRARY = {
    "Discovery": {
        "subjects": (
            "Metabolomics for early discovery decisions at {company}",
            "Biochemical readouts for discovery biology at {company}",
            "Understanding pathway activity in discovery at {company}",
            "Metabolomics around target biology at {company}",
            "A functional biology layer for discovery at {company}",
            "Connecting phenotype and biochemistry at {company}",
            "Discovery-stage metabolomics for {company}",
            "Broad biochemical profiling for early research at {company}",
            "Interpreting model biology in discovery at {company}",
            "Metabolic evidence for discovery programs at {company}",
        ),
        "narratives": (
            "Discovery work often turns on whether a phenotype reflects real pathway biology. Untargeted metabolomics can add a direct biochemical readout across cells, tissues, plasma, or other sample types, which can help teams see how a target or compound changes functional biology before larger investments are made.",
            "Early research teams often have strong genetic, transcriptomic, or assay data but still need to understand what is happening biochemically. Metabolomics can show which pathways are moving, where a model behaves as expected, and where the biology may need a closer look.",
            "When a discovery program produces a promising signal, the next question is usually whether the mechanism is durable enough to pursue. A broad metabolomics study can provide pathway-level evidence that supports target evaluation, compound selection, and follow-up experiments.",
            "Discovery groups frequently compare models, perturbations, and compounds across different experimental systems. Metabolomics can make those comparisons more concrete by measuring biochemical changes that sit close to phenotype and cellular function.",
            "A discovery assay can show that biology has changed, but it may not explain why. Metabolomics can add a functional layer that identifies altered pathways, unexpected compound effects, and biochemical patterns that may guide the next experiment.",
            "Many early programs need better evidence before moving from an interesting observation to a development plan. Metabolomics can help clarify whether the observed phenotype is connected to coherent pathway biology or a narrower model-specific effect.",
            "Target biology can look different across models and sample systems. A metabolomics readout can help compare those systems in practical terms by showing which biochemical pathways are conserved and which ones diverge.",
            "Discovery decisions are often made with incomplete biological context. Metabolomics can add broad, interpretable biochemical data that helps teams evaluate mechanism, prioritize compounds, and decide which hypotheses deserve more work.",
            "Phenotypic screens can identify activity without explaining the underlying biology. Metabolomics can help connect those phenotypes to pathway changes, giving scientists a clearer view of mechanism and possible downstream implications.",
            "In early research, small biochemical shifts can reveal whether a system is responding in the expected direction. Metabolomics can measure those shifts broadly and help teams understand target engagement, pathway modulation, and model relevance.",
        ),
    },
    "Translational / Clinical Development": {
        "subjects": (
            "Metabolomics across translational studies at {company}",
            "Connecting preclinical and clinical biology at {company}",
            "Biochemical evidence for development work at {company}",
            "Clinical sample metabolomics for {company}",
            "Functional readouts for translational programs at {company}",
            "Metabolomics in clinical development at {company}",
            "Understanding response biology at {company}",
            "Translational metabolomics support for {company}",
            "Pathway-level data for development teams at {company}",
            "Clinical biology signals in metabolomics at {company}",
        ),
        "narratives": (
            "Translational teams often need to know whether biology seen in models is also present in human samples. Metabolomics can provide a practical bridge by measuring pathway activity across preclinical and clinical settings with a consistent biochemical lens.",
            "Clinical development decisions are stronger when response, dose, and disease biology are understood together. Metabolomics can add functional evidence from patient samples that helps explain what changed during treatment and what may separate responder groups.",
            "A translational plan can be difficult when model data and clinical observations do not line up cleanly. Metabolomics can help identify shared biochemical signals, missing pathway activity, and patient biology that may not be captured by standard endpoints.",
            "Development teams often work with valuable samples and limited chances to extract more insight. A metabolomics study can add broad biochemical context without changing the original trial design or requiring a narrow single-marker hypothesis.",
            "Patient heterogeneity can make clinical results hard to interpret. Metabolomics can help show whether differences in response, progression, or baseline biology are tied to measurable pathway activity in the samples already being collected.",
            "Translational groups often need evidence that connects mechanism to clinical reality. Metabolomics can support that work by showing how disease biology and treatment effect appear in human biochemical profiles.",
            "When a program moves toward the clinic, teams need more than a promising mechanism. Metabolomics can help test whether the expected pathways are active in relevant samples and whether clinical biology supports the development strategy.",
            "Clinical samples can contain biochemical information that explains treatment effect, tolerability, or disease state. Metabolomics can help bring that information into development discussions in a form scientists and clinicians can interpret.",
            "A common development challenge is deciding what a clinical signal means biologically. Metabolomics can add pathway-level evidence that helps separate drug effect, disease activity, and patient-level variation.",
            "Translational studies often depend on connecting different evidence streams. Metabolomics can provide a measured biochemical layer that supports decisions across model selection, clinical sampling, responder analysis, and stage-gate review.",
        ),
    },
    "Biomarkers / Bioanalysis": {
        "subjects": (
            "Metabolomics for biomarker work at {company}",
            "Biochemical context for bioanalysis at {company}",
            "Functional biomarkers in clinical samples at {company}",
            "Metabolomics around PK and response at {company}",
            "Patient biology signals for {company}",
            "Broad profiling for biomarker teams at {company}",
            "Connecting analytes and pathway biology at {company}",
            "Metabolomics support for bioanalytical questions at {company}",
            "Biomarker discovery with biochemical data at {company}",
            "Interpretable metabolite markers for {company}",
        ),
        "narratives": (
            "Biomarker and bioanalysis teams often need markers that are measurable, interpretable, and connected to patient biology. Metabolomics can help identify biochemical signals tied to response, disease activity, exposure, or mechanism.",
            "Targeted assays are powerful, but they may not show the broader biology around a result. Metabolomics can place specific analytes, PK patterns, or pharmacodynamic signals into a wider pathway context.",
            "Clinical samples can carry biochemical evidence that helps explain why patients respond differently. Metabolomics can support biomarker discovery, patient stratification, and interpretation of pathway changes across cohorts.",
            "Bioanalytical work often focuses on precision around known measurements. Metabolomics can complement that work by showing adjacent biochemical changes that may explain exposure, response, tolerability, or disease state.",
            "A useful biomarker needs a clear biological story behind it. Metabolomics can help reveal whether a candidate marker reflects pathway activity, disease biology, treatment effect, or a sample-specific artifact.",
            "Many teams need to move from a long list of candidate biomarkers to a smaller set with biological meaning. Metabolomics can help prioritize signals that are coherent, measurable, and connected to functional pathways.",
            "Patient stratification is difficult when standard clinical variables do not explain enough variation. Metabolomics can add biochemical features that may help distinguish disease subtypes, response patterns, or baseline risk groups.",
            "PK and PD data can raise important biological questions. Metabolomics can help show whether exposure is translating into expected pathway effects and whether unexpected biochemical changes deserve follow-up.",
            "Biomarker programs often need evidence that stands up across sample types and study stages. Metabolomics can provide broad biochemical measurements that support discovery, verification, and clinical interpretation.",
            "When a single analyte does not tell the full story, pathway-level metabolomics can add context. This can help teams understand response biology, marker panels, and the functional meaning of clinical sample data.",
        ),
    },
    "Clinical Pharmacology": {
        "subjects": (
            "Metabolomics for clinical pharmacology at {company}",
            "Biochemical context for PK/PD at {company}",
            "Exposure-response biology at {company}",
            "Dose optimization with functional readouts at {company}",
            "Pharmacology insights from clinical samples at {company}",
            "Connecting exposure and pathway response at {company}",
            "Metabolomics around dose response at {company}",
            "Clinical pharmacology support for {company}",
            "Interpreting PK/PD signals at {company}",
            "Functional evidence for pharmacology teams at {company}",
        ),
        "narratives": (
            "Clinical pharmacology teams often need to connect exposure, dose, response, and mechanism in human samples. Metabolomics can add a functional biochemical layer that helps show whether pharmacokinetic patterns are translating into pathway-level effects.",
            "PK/PD interpretation is stronger when pharmacology data can be viewed alongside measured biology. Metabolomics can help identify biochemical changes that track with exposure, dose, response, or unexpected patient-level variation.",
            "Dose optimization often depends on understanding more than concentration and endpoint movement. Metabolomics can provide pathway-level evidence that helps teams evaluate whether a dose is producing the intended biological effect.",
            "Exposure-response questions can be difficult when clinical endpoints are delayed or variable. Metabolomics can add early biochemical context that helps explain response patterns across cohorts, dose groups, or time points.",
            "Clinical pharmacology work often bridges quantitative models and patient biology. Metabolomics can support that bridge by measuring downstream biochemical effects that can be compared with PK, PD, and clinical observations.",
            "When PK and PD signals do not line up cleanly, teams need additional biological context. Metabolomics can help reveal whether pathway activity, compensatory biology, or patient heterogeneity may explain the disconnect.",
            "Pharmacokinetic and pharmacodynamic data can point to important questions about mechanism. Metabolomics can help answer those questions by showing which biochemical pathways move with exposure and treatment response.",
            "Dose selection decisions benefit from evidence that is both quantitative and biologically interpretable. Metabolomics can add functional readouts that help clarify dose response and support pharmacology discussions.",
            "Clinical samples collected for pharmacology studies can contain broader biochemical information than a single endpoint captures. Metabolomics can help extract that context and connect it to exposure-response analysis.",
            "A pharmacology signal is easier to interpret when teams can see the biology behind it. Metabolomics can provide measured pathway data that supports PK/PD interpretation, dose optimization, and follow-up hypotheses.",
        ),
    },
    "Medical Affairs": {
        "subjects": (
            "Metabolomics evidence for medical affairs at {company}",
            "Disease biology context for {company}",
            "Biochemical data for scientific exchange at {company}",
            "Metabolomics in evidence generation at {company}",
            "Scientific context for clinical discussions at {company}",
            "Pathway evidence for medical teams at {company}",
            "Metabolomics around disease education at {company}",
            "Real biological context for {company}",
            "Supporting external scientific discussions at {company}",
            "Evidence generation with metabolomics at {company}",
        ),
        "narratives": (
            "Medical affairs teams often need evidence that explains disease biology in a clear and credible way. Metabolomics can provide measurable biochemical data that supports scientific exchange, education, and external research discussions.",
            "Clinicians and investigators usually respond best to evidence that is specific and biologically grounded. Metabolomics can help describe disease activity, treatment response, and pathway changes without relying on broad claims.",
            "Evidence generation often requires a practical connection between mechanism and patient biology. Metabolomics can add that connection by measuring biochemical differences across relevant clinical samples and cohorts.",
            "Medical teams may need to explain why a pathway matters in a disease setting. Metabolomics can provide examples of functional biology that make mechanism, heterogeneity, and response easier to discuss with scientific audiences.",
            "External engagement is stronger when the discussion is supported by real biological data. Metabolomics can help build a disease biology story based on measured pathway changes rather than abstract pathway diagrams.",
            "Many medical affairs plans include investigator studies, publication support, and education around disease mechanisms. Metabolomics can add biochemical evidence that helps those activities stay scientifically focused and clinically relevant.",
            "A good scientific exchange often starts with a clear question about patient biology. Metabolomics can help answer that question by showing how biochemical pathways differ by disease state, treatment group, or clinical phenotype.",
            "Medical affairs groups often need data that can be understood by both scientific and clinical stakeholders. Metabolomics can provide interpretable pathway-level evidence that supports balanced discussion of disease and treatment biology.",
            "When teams build evidence around a therapy area, they need more than isolated observations. Metabolomics can help connect clinical findings to biochemical pathways that investigators can evaluate and discuss.",
            "Disease education is more useful when it reflects measured biology. Metabolomics can support that work by identifying biochemical patterns that help explain patient heterogeneity, disease burden, and potential treatment effects.",
        ),
    },
    "Safety / Quality": {
        "subjects": (
            "Metabolomics for safety interpretation at {company}",
            "Biochemical context for quality questions at {company}",
            "Understanding safety biology at {company}",
            "Metabolomics around toxicity signals at {company}",
            "Pathway evidence for safety teams at {company}",
            "Biochemical profiling for risk assessment at {company}",
            "Safety and quality metabolomics for {company}",
            "Interpreting off-target biology at {company}",
            "Metabolic signals in safety studies at {company}",
            "Functional readouts for safety review at {company}",
        ),
        "narratives": (
            "Safety and quality teams often need to understand whether a signal reflects adaptive biology, off-target activity, or a risk that deserves follow-up. Metabolomics can add pathway-level evidence behind observed changes.",
            "A safety finding can be difficult to interpret when the mechanism is unclear. Metabolomics can help show which biochemical pathways are affected and whether the pattern is consistent with a known biological process.",
            "Toxicology and quality investigations often benefit from broader biochemical context. Metabolomics can help distinguish isolated variation from coherent pathway changes that may point to a specific mechanism.",
            "When teams review risk, they need data that clarifies biology rather than adding noise. Metabolomics can provide interpretable biochemical profiles that support follow-up decisions and cross-functional discussion.",
            "Unexpected findings can slow a program if the underlying biology is not understood. Metabolomics can help identify metabolic stress, organ-related pathway changes, or compensatory responses that may explain the observation.",
            "Safety studies often raise questions that are not answered by standard endpoints alone. Metabolomics can add a functional readout that helps connect exposure, tissue response, and potential mechanism.",
            "Quality issues can sometimes appear as subtle biological or biochemical differences across samples or processes. Metabolomics can help characterize those differences and support a more informed investigation.",
            "Risk assessment depends on understanding which signals matter. Metabolomics can help separate broad nonspecific changes from pathway patterns that suggest a clearer safety or quality concern.",
            "A mechanistic view of safety can help teams decide what to monitor next. Metabolomics can identify affected biochemical pathways and provide evidence for targeted follow-up studies.",
            "Safety review is more productive when teams can discuss biology directly. Metabolomics can provide measured pathway data that helps explain toxicity signals, tolerability questions, and potential off-target effects.",
        ),
    },
    "Oncology": {
        "subjects": (
            "Metabolomics for oncology studies at {company}",
            "Tumor metabolism and response at {company}",
            "Biochemical context in oncology at {company}",
            "Understanding resistance biology at {company}",
            "Metabolomics across oncology samples at {company}",
            "Pathway-level oncology data for {company}",
            "Cancer metabolism readouts at {company}",
            "Functional biology in oncology programs at {company}",
            "Metabolomics for tumor and host biology at {company}",
            "Oncology biomarker context for {company}",
        ),
        "narratives": (
            "Oncology programs often need to understand tumor metabolism, host response, treatment effect, and resistance biology at the same time. Metabolomics can add functional biochemical evidence across tissue, plasma, serum, or other clinical samples.",
            "Cancer biology can produce many molecular signals, but not all of them reflect active pathway changes. Metabolomics can help identify which biochemical pathways are moving with response, progression, or resistance.",
            "Responder analyses are stronger when teams can compare functional biology across patient groups. Metabolomics can help show whether metabolic pathways differ by response status, tumor biology, or treatment exposure.",
            "Resistance can be difficult to explain from genomic or expression data alone. Metabolomics can add a closer view of pathway activity that may help clarify escape mechanisms and downstream biological effects.",
            "Oncology studies often have limited samples and important mechanistic questions. Metabolomics can extract broad biochemical information from those samples and support interpretation of disease state, treatment effect, and patient heterogeneity.",
            "Tumor metabolism is central to many oncology questions, but it needs to be measured in the right biological context. Metabolomics can provide direct pathway data that complements molecular, imaging, and clinical endpoints.",
            "When a therapy changes tumor or immune biology, the biochemical effects may appear across multiple pathways. Metabolomics can help map those changes and identify patterns that are relevant to response or progression.",
            "Oncology teams often need evidence that connects mechanism to patient-level outcomes. Metabolomics can support that work by measuring biochemical differences across cohorts, time points, and treatment groups.",
            "Cancer samples can reflect both tumor-intrinsic metabolism and systemic host biology. Metabolomics can help separate and interpret those signals so teams can ask better follow-up questions.",
            "A clear pathway readout can make oncology data easier to interpret. Metabolomics can help connect biomarkers, resistance hypotheses, and clinical observations to measurable biochemical biology.",
        ),
    },
}


def get_narrative_set(persona: str) -> dict[str, tuple[str, ...]]:
    """Return subject and narrative variants for a supported persona."""
    return NARRATIVE_LIBRARY[persona]
