"""Persona content library for Andy Bot email generation."""

from __future__ import annotations

PERSONAS = (
    "Discovery",
    "Translational / Clinical Development",
    "Biomarkers / Bioanalysis",
    "Clinical Pharmacology",
    "Medical Affairs",
    "Safety / Quality",
    "Immunology",
    "Oncology",
)

NARRATIVE_LIBRARY = {
    "Discovery": {
        "subjects": (
            "Metabolomics for early discovery decisions at {company}",
            "Metabolomics for discovery biology at {company}",
            "Metabolomics around target biology at {company}",
            "Metabolomics for model selection at {company}",
            "Metabolomics for compound screening at {company}",
            "Metabolomics for early research at {company}",
            "Metabolomics for target validation at {company}",
            "Metabolomics for phenotype follow-up at {company}",
            "Metabolomics for discovery programs at {company}",
            "Metabolomics for mechanism work at {company}",
        ),
        "use_cases": (
            "compare disease models before advancing targets",
            "evaluate target engagement in cells, tissue, or plasma",
            "prioritize compounds after phenotypic screening",
            "study how perturbations affect metabolism",
            "select models that better represent disease biology",
            "check whether tool compounds produce expected effects",
            "connect genetic findings to metabolite-level evidence",
            "support hit-to-lead decisions with sample data",
            "identify follow-up experiments after a screen",
            "study target biology before larger program investment",
        ),
        "benefits": (
            "prioritize targets and compounds with stronger sample evidence",
            "compare models using metabolite-level data",
            "identify biology that may need follow-up before handoff",
        ),
    },
    "Translational / Clinical Development": {
        "subjects": (
            "Metabolomics across translational studies at {company}",
            "Metabolomics for clinical development at {company}",
            "Metabolomics for patient sample studies at {company}",
            "Metabolomics for responder analysis at {company}",
            "Metabolomics for development teams at {company}",
            "Metabolomics for trial sample interpretation at {company}",
            "Metabolomics for translational programs at {company}",
            "Metabolomics for dose and response studies at {company}",
            "Metabolomics for human sample biology at {company}",
            "Metabolomics for cohort comparisons at {company}",
        ),
        "use_cases": (
            "compare preclinical and clinical sample biology",
            "study responder and non-responder differences",
            "interpret baseline biology across patient cohorts",
            "evaluate treatment effects in collected trial samples",
            "support stage-gate decisions with human sample data",
            "connect dose groups with metabolite-level changes",
            "study disease progression signals across time points",
            "build evidence packages for development decisions",
            "evaluate subgroup biology using existing samples",
            "support translational plans across program stages",
        ),
        "benefits": (
            "compare biology across models and human samples",
            "study patient subgroups with quantitative metabolite data",
            "support development decisions using existing sample sets",
        ),
    },
    "Biomarkers / Bioanalysis": {
        "subjects": (
            "Metabolomics for biomarker work at {company}",
            "Metabolomics for bioanalysis teams at {company}",
            "Metabolomics for patient stratification at {company}",
            "Metabolomics for PK and response studies at {company}",
            "Metabolomics for biomarker discovery at {company}",
            "Metabolomics for clinical sample markers at {company}",
            "Metabolomics for analyte panel development at {company}",
            "Metabolomics for PD marker work at {company}",
            "Metabolomics for cohort biomarker analysis at {company}",
            "Metabolomics for marker prioritization at {company}",
        ),
        "use_cases": (
            "discover markers linked to response or disease activity",
            "prioritize candidate biomarkers for follow-up",
            "evaluate PD markers in clinical samples",
            "study exposure, response, and metabolite patterns together",
            "build analyte panels for patient stratification",
            "compare biomarker signals across cohorts",
            "support verification work with quantitative metabolite data",
            "investigate tolerability or response markers",
            "identify baseline features tied to patient groups",
            "connect assay findings with metabolite measurements",
        ),
        "benefits": (
            "prioritize candidate markers with biological relevance",
            "compare patient groups using quantitative metabolite data",
            "support panel design, verification, and follow-up assays",
        ),
    },
    "Clinical Pharmacology": {
        "subjects": (
            "Metabolomics for clinical pharmacology at {company}",
            "Metabolomics for PK/PD studies at {company}",
            "Metabolomics for exposure-response work at {company}",
            "Metabolomics for dose optimization at {company}",
            "Metabolomics for pharmacology samples at {company}",
            "Metabolomics for dose response at {company}",
            "Metabolomics for human pharmacology at {company}",
            "Metabolomics for cohort pharmacology at {company}",
            "Metabolomics for PK and biology studies at {company}",
            "Metabolomics for pharmacology decisions at {company}",
        ),
        "use_cases": (
            "connect exposure, dose, and metabolite-level response",
            "evaluate dose groups using clinical sample data",
            "study early biological effects before endpoint readouts",
            "interpret PK/PD differences across cohorts",
            "support dose selection with metabolite measurements",
            "compare time points in pharmacology studies",
            "investigate patient variability in exposure-response analyses",
            "evaluate whether treatment changes expected metabolites",
            "support model-informed decisions with sample evidence",
            "study pharmacology questions in human biospecimens",
        ),
        "benefits": (
            "connect exposure and dose with metabolite-level changes",
            "compare cohorts, time points, and dose groups",
            "support dose selection and PK/PD interpretation",
        ),
    },
    "Medical Affairs": {
        "subjects": (
            "Metabolomics evidence for medical affairs at {company}",
            "Metabolomics for disease biology at {company}",
            "Metabolomics for evidence generation at {company}",
            "Metabolomics for scientific exchange at {company}",
            "Metabolomics for investigator studies at {company}",
            "Metabolomics for publication support at {company}",
            "Metabolomics for external research at {company}",
            "Metabolomics for disease education at {company}",
            "Metabolomics for clinical discussion support at {company}",
            "Metabolomics for medical evidence plans at {company}",
        ),
        "use_cases": (
            "generate evidence for disease biology discussions",
            "support investigator-sponsored research",
            "compare patient cohorts for publication planning",
            "study treatment response in clinical samples",
            "build data packages for scientific exchange",
            "support disease education with sample-based evidence",
            "evaluate unmet need in defined patient groups",
            "develop external research hypotheses",
            "support congress and manuscript data generation",
            "study patient heterogeneity in therapeutic areas",
        ),
        "benefits": (
            "support scientific exchange with quantitative sample data",
            "strengthen evidence generation and publication planning",
            "describe patient cohorts with metabolite-level measurements",
        ),
    },
    "Safety / Quality": {
        "subjects": (
            "Metabolomics for safety interpretation at {company}",
            "Metabolomics for quality investigations at {company}",
            "Metabolomics for toxicity studies at {company}",
            "Metabolomics for risk assessment at {company}",
            "Metabolomics for safety teams at {company}",
            "Metabolomics for off-target assessment at {company}",
            "Metabolomics for tolerability questions at {company}",
            "Metabolomics for product quality studies at {company}",
            "Metabolomics for safety review at {company}",
            "Metabolomics for toxicology follow-up at {company}",
        ),
        "use_cases": (
            "investigate toxicity signals in study samples",
            "compare treated and control groups in safety studies",
            "study off-target effects using metabolite measurements",
            "support follow-up on tolerability findings",
            "evaluate product or process-related sample differences",
            "identify metabolic stress signals in preclinical studies",
            "support risk assessment with quantitative sample data",
            "compare organ-related metabolite changes across groups",
            "investigate unexpected findings before program decisions",
            "support quality investigations using biological samples",
        ),
        "benefits": (
            "investigate safety findings with quantitative metabolite data",
            "compare treatment, control, product, or process groups",
            "support risk assessment and follow-up study design",
        ),
    },

    "Immunology": {
        "subjects": (
            "Metabolomics for immunology studies at {company}",
            "Metabolomics for inflammation biology at {company}",
            "Metabolomics for immune response work at {company}",
            "Metabolomics for immunology biomarkers at {company}",
            "Metabolomics for immune-metabolic biology at {company}",
            "Metabolomics for inflammatory disease at {company}",
            "Metabolomics for immunology development at {company}",
            "Metabolomics for patient stratification at {company}",
            "Metabolomics for treatment response in immunology at {company}",
            "Metabolomics for translational immunology at {company}",
        ),
        "use_cases": (
            "study inflammatory pathway biology in patient samples",
            "compare immune-metabolic signals across cohorts",
            "evaluate lipid-mediated inflammation and treatment response",
            "identify baseline biology linked to response",
            "support patient stratification in inflammatory disease",
            "connect immune biology with metabolite-level evidence",
            "interpret on-treatment changes in clinical samples",
            "compare responder and non-responder biology",
            "study cardiometabolic or obesity-related inflammatory signals",
            "prioritize follow-up biomarkers for immunology programs",
        ),
        "benefits": (
            "interpret inflammatory and immune-metabolic pathway activity",
            "compare patient subgroups using quantitative metabolite data",
            "support response, stratification, and biomarker hypotheses",
        ),
    },
    "Oncology": {
        "subjects": (
            "Metabolomics for oncology studies at {company}",
            "Metabolomics for tumor metabolism at {company}",
            "Metabolomics for oncology response work at {company}",
            "Metabolomics for resistance biology at {company}",
            "Metabolomics for oncology samples at {company}",
            "Metabolomics for cancer metabolism at {company}",
            "Metabolomics for tumor and host biology at {company}",
            "Metabolomics for oncology biomarkers at {company}",
            "Metabolomics for cancer cohort studies at {company}",
            "Metabolomics for oncology development at {company}",
        ),
        "use_cases": (
            "study tumor metabolism and treatment response",
            "compare responders and non-responders in oncology cohorts",
            "investigate resistance using tissue, plasma, or serum samples",
            "evaluate tumor and host biology together",
            "support oncology biomarker discovery",
            "study metabolic differences across cancer subtypes",
            "compare baseline and on-treatment samples",
            "investigate immune and metabolic response signals",
            "support patient stratification in oncology studies",
            "evaluate progression-related metabolite changes",
        ),
        "benefits": (
            "compare responders, non-responders, and disease subgroups",
            "study tumor, host, and treatment biology in available samples",
            "support biomarker and resistance hypotheses with metabolite data",
        ),
    },
}


def get_narrative_set(persona: str) -> dict[str, tuple[str, ...]]:
    """Return subject, use case, and benefit variants for a supported persona."""
    return NARRATIVE_LIBRARY[persona]
